site_name: PyNGL - NCCA Python Graphics Library
nav:
  - Home: index.md
  - About: about.md
  - Math: Math.md
  - VAO: VAO.md
  - Shaders: Shaders.md
  - Geometry: Geometry.md
  - Camera: Camera.md
  - Image and Texture: ImageAndTexture.md
  - Text: Text.md
  - Miscellaneous: Misc.md
theme: readthedocs

plugins:
  - mkdocstrings
